<template>
<div>
<p style="text-align: center;"><strong><span style="font-size: 12.0pt; line-height: 107%; font-family: Helvetica;">GOPREP</span></strong></p>
<p style="text-align: center;"><strong><span style="font-size: 12.0pt; line-height: 107%; font-family: Helvetica;">TERMS OF SERVICE</span></strong></p>
<p style="text-align: center;"><strong><span style="font-size: 12.0pt; line-height: 107%; font-family: Helvetica;">Last Updated: February 17, 2019</span></strong></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">GoPrep provides an online platform for consumers (&ldquo;Users&rdquo;) to find and order weekly meals from meal preparation companies (the online platform shall hereinafter be referred to as the &ldquo;Company Service&rdquo;) via the Company website(s) offered from time to time at </span><span style="font-family: Helvetica;">http://goprep.com</span><span style="font-family: Helvetica;">&nbsp; and/or via an App (collectively, the &ldquo;Site,&rdquo; or &ldquo;Sites&rdquo;).&nbsp; The Company Service is owned and operated by </span><span style="font-family: Helvetica;">GoPrep</span><span style="font-family: Helvetica;">, (&ldquo;Company&rdquo; &ldquo;we&rdquo; or &ldquo;us&rdquo;).</span></p>
<p style="margin-bottom: 7.5pt; text-align: justify; line-height: normal; background: white;"><span style="font-family: Helvetica;">Your use of the Service is subject to the terms and conditions set forth in these Terms of Service (the &ldquo;Terms of Service&rdquo;).&nbsp; </span></p>
<p style="margin-bottom: 7.5pt; text-align: justify; line-height: normal; background: white;"><strong><span style="font-family: Helvetica;">PLEASE READ THE TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING ANY PART OF THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY ALL THE TERMS OF THE TERMS OF SERVICE. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, EXIT THIS PAGE AND DO NOT ACCESS OR USE THE SERVICE. USE OF THE SERVICE IS EXPRESSLY CONDITIONED UPON YOUR ACCEPTANCE OF THE TERMS OF SERVICE.&nbsp; UNLESS SPECIFICALLY NOTED HEREIN ALL TERMS CONTAINED WITH THESE TERMS OF SERVICE SHALL APPLY TO USERS AND THIRD-PARTY PROVIDERS.</span></strong></p>
<ol>
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Updates to Terms of Service; Integration</span></strong><span style="font-family: Helvetica;">. We may, in our sole discretion, modify the Terms of Service via email or by posting notice on any part of the Company Service. The &ldquo;Last Updated&rdquo; date at the top the Terms of Service indicates when the latest modifications were made to the Terms of Service. By continuing to access and use the Company Service you agree to any such modifications. Therefore, you are responsible for reviewing and should become familiar with any such modifications. You are encouraged to review this Terms of Service periodically and to check the &ldquo;Last Updated&rdquo; date at the top of the Terms of Service for the most recent version. In addition, when using services or features on the Company Service, you will be subject to any posted guidelines or policies applicable to such services or features that may be posted from time to time, including but not limited to the Privacy Policy as noted below. All such guidelines or policies are hereby incorporated by reference into these Terms of Service.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Service Availability</strong>. The Company Service may be modified, updated, interrupted, suspended or discontinued at any time without notice or liability. If the Company Service were discontinued at any time, all data may be deleted.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Privacy Policy</strong>. Use of the Company Service is subject to the terms of our <u><span style="color: #4f81bd;"><a href="http://goprep.com/privacy-policy" target="_blank">Privacy Policy</a></span></u> which is hereby incorporated into and made part of these Terms of Service. Please carefully review our Privacy Policy. By using or accessing the Company Service, you agree to be bound by the terms of our Privacy Policy.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Age.</strong> The Company Service is meant for those at least eighteen (18) years of age and legally capable of entering into binding contracts.&nbsp; Use of the Company Service by anyone under this age is a violation of the Terms of Service.&nbsp; You may not use the Company Service if we have previously banned you from use of the Company Service or closed your account.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Intellectual Property</strong>. </span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">5.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You acknowledge that all materials on the Sites, including, but not limited to, the website design, application design, graphics, text, sounds, pictures, and other files and the selection and arrangement thereof (collectively, &ldquo;Materials&rdquo;), are the property of Company and/or its licensors, and are subject to and protected by United States and international copyright and other intellectual property laws and rights. All rights to Materials not expressly granted in these Terms of Service are reserved to their respective copyright owners. Company authorizes you to view, download and/or print the Materials provided that you keep intact all copyright and other proprietary notices contained in the original Materials. Except as expressly authorized by the Terms of Service, you may not copy, reproduce, distribute, republish, download, perform, display, post, transmit, scrape, copy, exploit, create derivative works or otherwise use any of the Materials in any form or by any means, without the prior written authorization of Company or the respective copyright owner.&nbsp; In the absence of a written agreement, you may not modify or adapt the Materials in any way or otherwise use them for any public or commercial resale purposes. The trademarks, service marks, trade names, trade dress and logos (collectively, &ldquo;Marks&rdquo;) contained or described in the Company Service are the sole property of Company and/or its licensors and may not be copied, altered or otherwise used, in whole or in part, without the prior written authorization of Company and/or its licensors. Company reserves the right to enforce its intellectual property rights fully under the law.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">5.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Your use of the Company Service is solely and exclusively under a limited license granted herein and you will not obtain any ownership interest therein through the Terms of Service or otherwise.&nbsp; All trademarks, service marks, trade names, domain names, slogans, logos, and other indicia of origin that appear on or in connection with any aspect of the Company Service are either the property of Company, its affiliates or licensors. Company retains the right to rescind and terminate the limited license granted hereunder at any point, for any reason. All rights not expressly granted herein by Company to you are fully reserved by Company, its advertisers and licensors.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">5.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Some of the company and product names, logos, brands, and other trademarks featured or referred to within the Company Service may not be owned by us and are the property of their respective trademark holders.&nbsp; These trademark holders are not affiliated with, nor do they sponsor or endorse the Service.</span></p>
<ol start="6">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Use of the Company Service, General</span></strong></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">6.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You will be required to establish an account to use the Company Service and/or take advantage of certain features.&nbsp; If so, you agree:</span></p>
<ol>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> to provide true, accurate, current and complete information about yourself as prompted by the Service; </span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> as permitted, to maintain and promptly update such information. If you provide any information that is false, inaccurate or outdated, or Company has reasonable grounds to suspect that such information is false, inaccurate or outdated, Company has the right to suspend or terminate your account and prohibit all current or future use of the Company Service by you; </span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> that your account is for your personal and/or business use. You may not resell the Service. </span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> that by creating an account, you agree to receive certain communications in connection with the Service.</span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">6.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your account. Your account is meant to be private and you shall not share accounts for any reason. You agree to immediately notify us of any unauthorized use of your password or account or any other breach of security. You agree to be responsible for all charges resulting from the use of your account via the Service, including charges resulting from unauthorized use of your account.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">6.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You may not do any of the following while accessing or using the Service: </span></p>
<ol>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> access, tamper with, or use non-public areas of the Service, our computer systems, or the technical delivery systems of our providers; </span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures; </span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> access or search or attempt to access or search the Service by any means other than through our currently available, published interfaces that are provided by us, unless you have been specifically allowed to do so in a separate agreement with us; </span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Service to send altered, deceptive or false source-identifying information;</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> disrupt or interfere with the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Company Service, or otherwise creating an undue burden on the Company Service.</span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">6.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You may not use manual or automated software, devices, or other processes to &ldquo;crawl,&rdquo; &ldquo;scrape,&rdquo; or &ldquo;spider&rdquo; any page of the Company Service. You will not decompile, reverse engineer, or otherwise attempt to obtain the source code of any part of the Company Service.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">6.5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Your use of the Company Service is at your own risk, including the risk that you might be exposed to Content that is offensive, indecent, inaccurate, objectionable, or otherwise inappropriate.</span></p>
<ol start="7">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Use of the Company Service, Third-Party Providers.</span></strong></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">7.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Third-Party Providers alone are responsible for identifying, understanding, and complying with all laws, rules and regulations that apply to their businesses and the listings related to the food goods and services (&ldquo;Third-Party Products&rdquo; or &ldquo;Products&rdquo;). You are responsible for obtaining any such permits, licenses or other governmental authorizations as may be required.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">7.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Information regarding the Third-Party Products shall be accurate in all regards including descriptions, photos, and any other representations of Third-Party Products.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">7.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You are solely responsible for establishing the price for the Third-Party Products.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">7.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Company makes no representations as to the display of your Products regarding frequency or placement.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">7.5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As a Third-Party Provider providing information regarding your Products on the Site, you understand that we are providing the Company Service for the purposes of facilitating opportunities for you to connect with the general public.&nbsp; You agree and acknowledge that the Company is not a party to any transactions you may enter into using the Company Service, except as may otherwise be stated herein, and shall not under any circumstances be liable for any damages of any kind arising out of, or in connection with, or relating to, the products and services you may be providing to the public.</span></p>
<ol start="8">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Use of the Company Service, Users.</span></strong></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">8.1<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong>Third-Party Websites</span></p>
<ol>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> Links provided via the Company Service to Third-Party websites, Third-Party Meal Preparation companies or others (the &ldquo;Third-Party Providers&rdquo;) are provided only as a convenience. If you use these Third-Party Providers or use links to such websites, you may leave the Company Service. Company does not control nor endorse any such Third-Party Providers. You agree that the Company Parties, as defined below, will not be responsible or liable for any content, goods or services provided by such Third-Party Providers or for your use or inability to use such Third-Party websites.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> You will use such links at your own risk. You are advised that other websites on the Internet, including Third-Party websites linked from the Company Service, might contain material or information: that some people may find offensive or inappropriate; that is inaccurate, untrue, misleading or deceptive; or that is defamatory, libelous, infringing of others&rsquo; rights or otherwise unlawful. Company expressly disclaims any responsibility for the content, legality, decency or accuracy of any information, and for any products and services, that appear on any Third-Party website or in advertisements or content that Third-Party websites may have in the Company Service.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> Your interactions Third-Party Providers found on or through the Company Service, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such parties. You agree and acknowledge that Company is not a party to any transactions you may enter into, except as may otherwise be stated herein.&nbsp; Company shall not under any circumstances be liable for any damages of any kind arising out of, or in connection with, or relating to, the products and services of a Thirty-Party Provider.</span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">8.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ordering, Processing</span></p>
<ol>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> Compiling your Order:&nbsp;Once you have selected the Products you wish to order from the Third-Party Provider and provided any other required information, you will be given the opportunity to submit your order. It is important that you check all the information that you enter and correct any errors before clicking or selecting submit.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> Amending or cancelling your Order:&nbsp;Once you have submitted your Order and your payment has been authorized, you will not be entitled to change or cancel your Order via the Company Service.&nbsp; In the event you wish to amend or cancel your order, you must do so directly with the Third-Party Provider. </span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Payment methods:&nbsp;Payment for Orders must be made in a manner as chosen by the Third-Party Provider.&nbsp; Payment for orders will be processed by the Third-Party Providers and the Company is not involved in any such transactions.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> Delivery of your Order:&nbsp;Estimated times for deliveries are provided by the Third-Party Providers. </span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> Company is not responsible for any errors in pricing displayed on the Company Service by Third-Party Providers.&nbsp; Any disputes between Users and Third-Party Providers shall be resolved between those Parties and the Company is not a party to any transactions between the Parties.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Suggestions and Improvements</strong>. By sending us any ideas, suggestions, documents or proposals (&ldquo;Feedback&rdquo;), you agree that (i) your Feedback does not contain the confidential or proprietary information of third parties, (ii) we are under no obligation of confidentiality, express or implied, with respect to the Feedback, (iii) we may have something similar to the Feedback already under consideration or in development, and (iv) you grant us an irrevocable, non-exclusive, royalty-free, perpetual, worldwide license to use, modify, prepare derivative works, publish, distribute and sublicense the Feedback, and you irrevocably waive, and cause to be waived, against Company and its users any claims and assertions of any moral rights contained in such Feedback.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Content.</strong> </span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">10.1&nbsp;&nbsp;&nbsp;&nbsp; All Content (as further defined below) on the Site is the sole responsibility of the person who originated such content. You acknowledge that all Content transmitted or accessed by you using the Company Services is at your own risk and you will be solely responsible and liable for any damage or loss to you or any other party resulting therefrom. You remain solely responsible for all Content that you transmit in connection with the Company Service, and you warrant that you possess all rights necessary to provide such Content and that you do not violate any third party&rsquo;s rights in providing such Content. We reserve the right to remove, and to allow certain users to remove, any objectionable Content in our sole discretion.&nbsp; </span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">10.2&nbsp;&nbsp;&nbsp;&nbsp; You understand that by providing Content publicly in connection with the Company Service you hereby grant us a non-exclusive, worldwide, royalty free, perpetual, irrevocable, sublicensable and transferable right to fully exploit such Content (including all related intellectual property rights) in connection with our business. For purposes of these Terms of Service, the term &ldquo;Content&rdquo; includes, without limitation, any information, text, reviews, videos, audio clips, comments, information, data, photographs, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible through the Company Service. Company and its licensees may publicly display advertisements and other information adjacent to or included with your Content. You are not entitled to any compensation for such advertisements. The manner, mode and extent of such advertising are subject to change without specific notice to you.</span></p>
<ol start="11">
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Representations.</strong> You expressly represent, warrant, and/or acknowledge that: </span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">11.1 &nbsp;&nbsp;&nbsp; Company does not warrant or guarantee the suitability or availability of any Material or Content, including without limitation any, data, products or services, found through the Company Service. </span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">11.2&nbsp;&nbsp;&nbsp;&nbsp; Company does not screen the authenticity or quality of any Material or Content or any provider of Material or Content, including, data, products or services found through the Company Service.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">11.3&nbsp;&nbsp;&nbsp;&nbsp; Company makes no representations or promises regarding any Material or Content, and that many of the Material or Content provided via the Company Service may be owned or licensed by third parties.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">11.4&nbsp;&nbsp;&nbsp;&nbsp; Company is not a party to any transaction between you and any provider of products or services via the Company Service.&nbsp; Any dispute shall be resolved between yourself and the provider of such products or services or your customer.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">11.5&nbsp;&nbsp;&nbsp;&nbsp; Any information, including any data, Materials, or Content on the Company Service, including on any Facebook, Instagram or Twitter page, are for informational purposes only.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">11.6&nbsp;&nbsp;&nbsp;&nbsp; You assume all risk when using the Company Service, including all the risks associated with any online or offline interactions with other users, providers of products and services, and from additional fees or charges from your mobile carrier.</span></p>
<ol start="12">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Warranties, Disclaimers and Limitations of Liability</span></strong><span style="font-family: Helvetica;">. You expressly understand and agree that:</span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">12.1&nbsp;&nbsp;&nbsp;&nbsp; Your use of the Company Service is at your sole risk. the Company Service and the associated materials and content are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. except as otherwise expressly provided in these Terms of Service, company, its parent, subsidiary and other affiliated companies, and their respective officers, directors, employees, agents and other representatives (collectively, the &ldquo;Company Parties&rdquo;) expressly disclaim all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a purpose and non-infringement. without limiting the generality of the foregoing, the company parties make no warranty that: (i) the Company Service will meet your requirements; (ii) the Company Service will be uninterrupted, timely, secure, or error-free; (iii) information that may be obtained via the Company Service will be accurate or reliable; (iv) the quality of any and all products, services, information or other material, including all merchandise, goods and services, obtained or purchased by you directly or indirectly through the Company Service will meet your expectations or needs; and (v) any errors in the Company Service will be corrected.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">12.2&nbsp;&nbsp;&nbsp;&nbsp; The Company Parties shall not under any circumstances be liable for any damages of any kind arising out of, in connection with or relating to the use of or inability to use the Company Service, including any liability: (i) as a publisher of information; (ii) for any incorrect or inaccurate information or any &lsquo;bug&rsquo; of the Company Service; (iii) for any unauthorized access to or disclosure of your transmissions or data; (iv) for statements or conduct of any third party on or via the Company Service; (v) for any disputes between users of the Company Service or between a user of the Company Service and a third party; or (vi) for any other matter relating to the Company Service or any third party. this is a comprehensive limitation of liability that applies to all damages of any kind, including any direct, indirect, special, incidental or consequential damages, whether based on breach of contract, breach of warranty, tort (including negligence), product liability or otherwise, even if an individual advises the company parties of the possibility of such damages. the limitations of liability set forth herein are fundamental elements of the basis of the bargain between company and you. the products, information and Company Service offered on and through the Company Service would not be provided to you without such limitations.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">12.3&nbsp;&nbsp;&nbsp;&nbsp; Notwithstanding the foregoing, the sole and entire maximum liability of the Company Parties for any reason, and your sole and exclusive remedy for any cause or claim whatsoever, shall be limited to twice the charges paid by you directly to Company for any particular Order or $100, whichever is less.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">12.4&nbsp;&nbsp;&nbsp;&nbsp; You agree that regardless of any statute or law to the contrary, any claim you may bring must be filed within one (1) year after the cause of action accrues or it will be permanently barred.</span></p>
<ol start="13">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Additional Disclaimers</span></strong></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">13.1&nbsp;&nbsp;&nbsp;&nbsp; Allergy, dietary and other product information. Third-Party Providers are responsible for providing Information about their Products and ensuring that it is factually accurate and up-to-date, and we do not undertake any such responsibility. If you are in doubt about allergy warnings, contents of a dish or any other Product Information, you should confirm with the Third-Party Provider directly before ordering.</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">13.2&nbsp;&nbsp;&nbsp;&nbsp; Third-Party Providers actions and omissions: The legal contract for the supply and purchase of Products is between you and the Third-Party Providers that you place your Order with. We have no control over the actions or omissions of any Third-Party Providers. </span></p>
<ol start="14">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Indemnification.</span></strong><span style="font-family: Helvetica;"> You agree to indemnify, defend and hold harmless the Company Parties against all claims, demands, causes of action, losses, expenses, damages and costs (including any reasonable attorneys&rsquo; fees), resulting or arising from or relating to your use of the Company Service, any activity related to your account by you or any other person permitted by you, any Material that you submit to, post on or transmit through the Company Service, your breach of these Terms of Service, your infringement or violation of any rights of another, or termination of your access to the Company Service. We reserve the right to assume, at our sole expense, the exclusive defense and control of any such claim or action and all negotiations for settlement or compromise, and you agree to fully cooperate with us in the defense of any such claim, action, settlement or compromise negotiations, as requested by us.</span></li>
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Termination</span></strong><span style="font-family: Helvetica;">. You may terminate your use of the Company Service at any time. You agree that Company may terminate or suspend your access to all or part of the Company Service, with or without notice, in our reasonable discretion, at any time.&nbsp; Company reserves the right to modify or discontinue the Company Service (or any part thereof) with or without notice, at any time. Following the termination or cancellation of your subscription to the Company Service and/or your account, we reserve the right to delete all your data in the normal course of operations.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Procedure for Notifying the Company of Copyright Infringement</strong>. Those who believe that their copyrighted work has been infringed or are aware of other infringing material, should contact our Copyright Agent at the address listed below and provide us with the following information:</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> An electronic or physical signature of a person authorized to act on behalf of the owner of the copyrighted work that has allegedly been infringed.</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> Identification of the copyrighted work claimed to have been infringed.</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> Information describing where the allegedly infringing material is located on the Service.</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> Your address, telephone number, and email address.</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> A written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.</span></li>
<li style="text-align: justify; text-indent: .5in;"><span style="font-family: Helvetica;"> A statement by you that the above information in your notification is accurate and that, under penalty of perjury, you are the copyright owner or authorized to act on the copyright owner&rsquo;s behalf. The foregoing information may be emailed or mailed to our Copyright Agent at the addresses listed at the end of this Terms of Service.</span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">Following receipt of the information listed above, we will remove or disable access to the infringing material and take reasonable steps to notify the user responsible for posting said material. The posting of infringing copyrighted material may result in the termination of user privileges of such user.</span></p>
<ol start="17">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Force Majeure.</span></strong></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">A party will be not being considered in breach or in default because of and will not be liable to the other party for, any delay or failure to perform its obligations under this agreement by reason of fire, earthquake, flood, explosion, strike, riot, war, terrorism, or similar event beyond that party&rsquo;s reasonable control (each a &ldquo;Force Majeure Event&rdquo;). However, if a Force Majeure Event occurs, the affected party shall, as soon as practicable: </span></p>
<ol>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> notify the other party of the Force Majeure Event and its impact on performance under this agreement; and</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> use reasonable efforts to resolve any issues resulting from the Force Majeure Event and perform its obligations under this agreement.&nbsp;&nbsp; </span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> <strong>Applicable Law and Jurisdiction</strong>. </span></li>
</ol>
<p style="text-align: justify;"><span style="font-family: Helvetica;">Your use of the Service is governed by and will be enforced under the laws of the State of New York without regard to its conflict of law provisions. You agree to submit to the personal and exclusive jurisdiction of the courts located within this stated Jurisdiction.&nbsp; You agree that printed copies of any and all agreements and/or notices in electronic form are admissible in any legal or regulatory proceedings.&nbsp; Any controversy, claim, suit, injury or damage arising from or in any way related to the Company Service or these Terms of Service shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association then in effect and before a single arbitrator located in or near Brooklyn, New York. Any such controversy, claim, suit, injury or damage shall be arbitrated on an individual basis and shall not be consolidated in any arbitration with any controversy, claim, suit, injury or damage of any other party. Company may seek any interim or preliminary relief from a court of competent jurisdiction listed above necessary to protect its rights pending the completion of arbitration. Each party shall assume its own costs of arbitration. IN ANY CLAIM, ACTION OR PROCEEDING TO ENFORCE ANY RIGHT OR OBLIGATION OF THE PARTIES UNDER THE TERMS OF SERVICE INCLUDING, WITHOUT LIMITATION, RELATING TO YOUR USE OF THE SERVICE, YOU HEREBY WAIVE ANY RIGHT YOU MAY NOW HAVE OR HEREAFTER POSSESS TO A TRIAL BY JURY.</span></p>
<ol start="19">
<li style="text-align: justify;"><strong><span style="font-family: Helvetica;"> Miscellaneous.</span></strong><span style="font-family: Helvetica;"> These Terms of Service constitute the entire agreement between Company and each user of the Service with respect to the subject matter of these Terms of Service.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> If any provision of these Terms of Service shall be deemed unlawful, void or for any reason unenforceable by a court of competent jurisdiction, the validity and enforceability of any remaining provisions will not be affected.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> The failure of the Company Parties to insist upon strict adherence to any term of these Terms of Service shall not constitute a waiver of such term and shall not be considered a waiver or limit that party&rsquo;s right thereafter to insist upon strict adherence to that term or any other term contained in these Terms of Service.&nbsp; You may not assign your obligations or rights hereunder to another entity or individual. We may transfer, assign or delegate these Terms of Service and its rights and obligations without your consent.</span></li>
<li style="text-align: justify;"><span style="font-family: Helvetica;"> No agency, partnership, joint venture, or employment is created as a result of these Terms of Service and you do not have any authority of any kind to bind us in any respect whatsoever.</span></li>
<li style="margin-bottom: .0001pt; text-align: justify;"><strong><span style="font-family: Helvetica;"> Customer Service.</span></strong><span style="font-family: Helvetica;"> If you have any comments or questions regarding these Terms of Service or wish to report any violation of these Terms of Service, you may contact us at the address below.</span></li>
</ol>
<p style="margin-bottom: .0001pt; text-align: justify;"><span style="font-family: Helvetica;">&nbsp;</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">Email Address: <a href="mailto:info@goprep.com">info@goprep.com</a></span></p>
<p style="margin-bottom: .0001pt; text-align: justify;"><span style="font-family: Helvetica;">&nbsp;</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">&nbsp;</span></p>
<p style="text-align: justify;"><span style="font-family: Helvetica;">&nbsp;</span></p>
</div>
</template>

<script>
export default {

  data () {
    return {

    }
  },
  methods: {

    },
}
</script>