<p><strong>SERVICES AGREEMENT&nbsp; </strong><span style="font-weight: 400;">&nbsp;</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">THIS&nbsp; SERVICES AGREEMENT (this &ldquo;Agreement&rdquo;) effective {{ date }} is between My Quick Startup LLC, doing business as GoPrep.com, a New York LLC with an address of 1622 Bay Ridge Avenue, Brooklyn, New York 11024&nbsp; (the &ldquo;Company&rdquo; or &ldquo;we&rdquo; or &ldquo;us&rdquo;) and, {{ companyName }}&nbsp; with an address of {{companyAddress}} (the &ldquo;Service Provider&rdquo; or &ldquo;you&rdquo;).&nbsp;</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">RECITALS&nbsp;</span></p>
<p>&nbsp;</p>
<p><strong>WHEREAS; </strong><span style="font-weight: 400;">the Company provides an online platform enabling the general public to place orders for meal preparation;&nbsp;</span></p>
<p>&nbsp;</p>
<p><strong>WHEREAS; </strong><span style="font-weight: 400;">the Service Provider provides meal preparation services in the territory from where such orders originate;</span></p>
<p>&nbsp;</p>
<p><strong>&nbsp;WHEREAS;</strong><span style="font-weight: 400;"> the Company wishes to provide access to the Service Provider for fulfilment of such orders;&nbsp;</span></p>
<p>&nbsp;</p>
<p><strong>WHEREAS;</strong><span style="font-weight: 400;"> the Service Provider wishes to fulfill orders for such orders;</span></p>
<p>&nbsp;</p>
<p><strong>NOWTHEREFORE, </strong><span style="font-weight: 400;">in consideration of the promises and other good and valuable consideration, &nbsp; the sufficiency and receipt of which are hereby acknowledged, the parties agree as follows:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;"><br /></span><strong>1. </strong><strong>GOPREP SERVICES</strong></li>
</ul>
<p><span style="font-weight: 400;">1.1&nbsp; &nbsp; </span> <span style="font-weight: 400;">GoPrep provides access to Customers (who may consist of consumers, organizations or companies or any third parties) expressing interest in meal preparation services (&ldquo;Service Requests&rdquo;).&nbsp;</span></p>
<p><span style="font-weight: 400;">1.2&nbsp; &nbsp; </span> <span style="font-weight: 400;">GoPrep may send you a communication regarding a Customer&rsquo;s Service Request that contains information about what service has been requested and customer&rsquo;s contact information (an &ldquo;Order&ldquo;).&nbsp;</span></p>
<p><span style="font-weight: 400;">1.3&nbsp; &nbsp; </span> <span style="font-weight: 400;">Orders will be sent to you based on the information you submit during your creation of a Company Profile on the GoPrep website.&nbsp;</span></p>
<p><span style="font-weight: 400;">1.4&nbsp; &nbsp; </span> <span style="font-weight: 400;">We do not guarantee to provide you with any specific number of Orders, nor do we provide any guarantees, representations or warranties regarding a customer's level of interest, their desire to have services completed, their ability to pay you, the accuracy of the information provided by the customers, or that any customers will hire you to perform services, nor do we guarantee that you will successfully contact each customer.&nbsp;</span></p>
<p><span style="font-weight: 400;">1.5&nbsp; &nbsp; </span> <span style="font-weight: 400;">We are not involved in, nor do we have any responsibility for your contracts with customers, their creditworthiness, or any payments to you or any disputes they may have with you or you may have with them. Company is free to contract with other Service Providers as this is not an exclusive contract.&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<ul>
<li><strong><strong>2. SERVICE PROVIDER SERVICES</strong></strong></li>
</ul>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">2.1&nbsp; &nbsp; &nbsp; </span> <span style="font-weight: 400;">Representations and Warranties. You represent and warrant that you have all requisite power and authority to enter into this Agreement and to sell the goods or provide the services which are the subject of the Service; where applicable, you are legally and properly licensed to and possesses all requisite licenses and permits to complete the Services in the geographic areas in which the work is located.&nbsp;</span></p>
<p><span style="font-weight: 400;">2.2&nbsp; &nbsp; &nbsp; </span> <span style="font-weight: 400;">Liability Coverage. You have a valid policy of liability insurance (in coverage amounts consistent with all applicable legal requirements) that names or schedules you for the operation of the Services and the coverage of all damages that can incur while you are performing the Services.</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;"><br /></span><strong>3. </strong><strong>PRICING</strong><strong>.</strong></li>
</ul>
<p><span style="font-weight: 400;">3.1 Customer payments (the &ldquo;Payments&rdquo;) shall be collected by the Company and processed via a gateway of our choosing which is currently Stripe. The Customer may also opt in to process payments with their preferred gateway for an additional monthly fee.&nbsp;</span></p>
<p><span style="font-weight: 400;">3.2 The Company fee is a percentage based on an aforementioned agreement between the Company and the Service Provider based on the gross order amount, minus the processing and shipping fees. There is an additional two and nine-tenth percent (2.9%) and .30 cents credit card processing fee per transaction if the Customer is using the standard Stripe Connect payment processing.&nbsp;</span></p>
<p><span style="font-weight: 400;">3.3 100% minus 2.9% and .30 cents plus the transaction fee percentage agreed upon by the Company and the Service Provider shall be paid to Service Provider at the time of payment by the customer.&nbsp;</span></p>
<p><span style="font-weight: 400;">3.4 Pricing is subject to change at the discretion of the Company upon sixty (60) days&rsquo; written notice to Service Provider.&nbsp;</span></p>
<p><span style="font-weight: 400;">3.5 The Customer may also choose to pay a flat monthly fee based on the amount of monthly orders collected, with no additional percentage per transaction with the exception of credit card processing fees from Stripe or the Customer&rsquo;s preferred payment processor. Flat monthly fees are billed automatically from the Customer&rsquo;s connected Stripe account balance per month or with a provided credit card that will be kept on file.&nbsp;</span></p>
<p><span style="font-weight: 400;">3.6 A Customer may also choose to pay a flat rate for any extended period of time, such as three months, six months, or one year. In this case the Customer must pay the agreed upon amount at the commencement of the contract for access to the Service Provider&rsquo;s platform for the agreed upon amount of time. The Customer will be charged recurringly after the agreed upon duration of time has expired. Any cancellation of services before the duration has expired does not warrant a refund.</span></p>
<p><span style="font-weight: 400;">3.7 For cancellation of services, the Customer must contact their sales representative or </span><a href="mailto:support@goprep.com"><span style="font-weight: 400;">support@goprep.com</span></a><span style="font-weight: 400;"> before their scheduled charge date has renewed.</span></p>
<p><span style="font-weight: 400;">3.8 Sales Tax. GoPrep automatically determines each store's state sales tax based on an external node module integrated from npmjs.com. Each store on our&nbsp; platform has the ability to override this automatically determined rate with their own rate as well as remove the sales tax rate entirely. GoPrep is not responsible or liable for any discrepancies involving the incorrect use of sales tax as set by the store if the store decides to override the automatically determined rate. Store&rsquo;s are responsible for reporting their proper sales tax documents to the IRS and for paying all taxes that are due.&nbsp;</span></p>
<p><br /><br /></p>
<ol start="4">
<li><strong> INDEPENDENT CONTRACTOR</strong><strong>.</strong><span style="font-weight: 400;"> Parties are and shall remain independent contractors of the other and nothing contained in this Agreement shall be deemed to create an employer/employee, principal/agent, partnership or joint venture relationship between the parties.</span></li>
<li><strong> INTELLECTUAL PROPERTY.</strong> <span style="font-weight: 400;">As used in this Agreement, &ldquo;Inventions&rdquo; means any software, applications, inventions, discoveries, designs, developments, processes, improvements, enhancements, modifications, copyrightable or patent material, and trade secrets discovered or created by you in connection with your duties at Company, whether discovered or created alone or in conjunction with others.&nbsp; You agree that any such Invention is done as a "work for hire" as that term is defined under U.S. law, and that as a result Company shall own all rights therein and thereto. To the extent any Invention does not qualify as a work for hire under applicable law, and to the extent any Invention is subject to copyright, patent, trade secret, or other proprietary right protection, you hereby assign, and agree to assign, all rights therein to Company. You will make prompt and full disclosure to Company, and will hold in trust for Company&rsquo;s sole benefit, any Inventions.&nbsp; You agree to execute and deliver such documents and take such other action as may be required or requested by Company to carry out the terms of this Section five.</span></li>
</ol>
<p><span style="font-weight: 400;">The Service Provider agrees to take no legal action under and circumstances against the Company for any claims involving disputes between the Service Provider and their Customers, any use of the Service Providers content on the Company&rsquo;s server, any intellectual property or proprietary claims of ownership over the design, structure, function and usage of the application, and any potential technical issues that may cause disruption to the Service Provider services.</span></p>
<ol start="6">
<li><strong> TERM AND TERMINATION</strong><strong>.</strong><span style="font-weight: 400;"> This Agreement shall remain in effect until terminated by either party upon thirty (30) days&rsquo; written notice</span></li>
<li><strong> INDEMNITY.</strong></li>
</ol>
<p><span style="font-weight: 400;">7.1&nbsp; &nbsp; &nbsp; </span> <span style="font-weight: 400;">Service Provider shall protect, indemnify, defend and hold the Company, including its affiliates and subsidiaries, officers, directors, shareholders, members, employees, agents, representatives, successors and assigns harmless from and against any and all penalties, claims, losses, liabilities, damages, charges, costs and/or expenses (including, without limitation, attorneys&rsquo; fees and court costs) rising out of or resulted from or in any way or in any manner connected with or related to any acts or omissions of Service Provider.&nbsp;</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">7.2&nbsp; &nbsp; &nbsp; </span> <span style="font-weight: 400;">Company shall protect, indemnify, defend and hold the Service Provider, including its affiliates and subsidiaries, officers, directors, shareholders, members, employees, agents, representatives, successors and assigns harmless from and against any and all penalties, claims, losses, liabilities, damages, charges, costs and/or expenses (including, without limitation, attorneys&rsquo; fees and court costs) rising out of or resulted from or in any way or in any manner connected with or related to any acts or omissions of Company.</span></p>
<ul>
<li style="font-weight: 400;">&nbsp;</li>
</ul>
<ol start="8">
<li><strong> GOVERNING LAW, JURISDICTION</strong><strong>.</strong><span style="font-weight: 400;"> This Agreement shall in all respects be construed in accordance with and governed by the laws of the State of New York.&nbsp; Any suit involving any dispute or matter arising under this Agreement may only be brought in the courts of the aforementioned jurisdiction. Service Provider hereby consents to the exercise of personal jurisdiction by any such court with respect to any such proceeding.&nbsp; Any controversy, claim, suit, injury or damage arising from or in any way related to this Agreement shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association then in effect and shall be heard by a single arbitrator in or near the State of New York. Any such controversy, claim, suit, injury or damage shall be arbitrated on an individual basis and shall not be consolidated in any arbitration with any controversy, claim, suit, injury or damage of any other party. Company may seek any interim or preliminary relief from a court of competent jurisdiction in the aforementioned jurisdiction necessary to protect its rights pending the completion of arbitration. Each party shall assume its own costs of arbitration.</span></li>
<li><strong> FORCE MAJEURE</strong><strong>.</strong></li>
</ol>
<p><span style="font-weight: 400;">A party will be not being considered in breach or in default because of and will not be liable to the other party for, any delay or failure to perform its obligations under this agreement by reason of fire, earthquake, flood, explosion, strike, riot, war, terrorism, or similar event beyond that party&rsquo;s reasonable control (each a &ldquo;Force Majeure Event&rdquo;). However, if a Force Majeure Event occurs, the affected party shall, as soon as practicable:</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Notify the other party of the Force Majeure Event and its impact on performance under this agreement; and</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Use reasonable efforts to resolve any issues resulting from the Force Majeure Event and perform its obligations under this agreement.</span></li>
</ol>
<ol start="10">
<li><strong> MISCELLANEOUS</strong><strong>.</strong></li>
</ol>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">A. Entire Agreement; Modification.&nbsp; This Agreement sets forth the entire agreement and understanding of the parties hereto concerning the subject matter hereof, and, except as otherwise specifically provided below, supersedes all prior and contemporaneous correspondence, agreements, arrangements and understandings, both oral and written, between the parties hereto concerning the subject matter hereof.&nbsp; No modification hereof shall be binding upon the parties hereto except by written instrument duly executed by such parties or their duly authorized representatives.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">B. Invalidity of Particular Provisions.&nbsp; If any term or provision of this Agreement or the application thereof to any person or circumstance shall to any extent be invalid or unenforceable, the other terms of this Agreement, or the application of such terms or provisions to persons or circumstances other than those as to which it is held invalid or unenforceable, shall not be affected thereby, and each term and provision of this Agreement shall be valid and be enforced to the fullest extent permitted by law.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">C. Counterparts.&nbsp; This Agreement shall be accepted by Service Provider in accordance with checking the box below which is your acknowledgement and approval of the terms herein.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">D. Interpretation.&nbsp; The paragraph headings of this Agreement are inserted for convenience only and shall not constitute a part of this Agreement in construing or interpreting any provision hereof. Whenever the context requires, words used in the singular shall be construed to include the plural and vice versa, and pronouns of any gender shall be deemed to include and designate the masculine, feminine or neuter gender.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">E. Notices. All notices given under this Agreement must be in writing. A notice is effective upon receipt and shall be sent via one of the following methods: delivery in person, overnight courier service, certified or registered mail, postage prepaid, return receipt requested, or by any other means agreed to by the Parties, such as email.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">F. This agreement will become effective when the Service Provider checks the box below. The date this agreement is agreed to by the Service Providers (as indicated by the date associated with that party&rsquo;s checking the box below) will be deemed the Execution Date of this agreement.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">G. Each party shall use all reasonable efforts to take, or cause to be taken, all actions necessary or desirable to consummate and make effective the transactions this agreement contemplates or to evidence or carry out the intent and purposes of this agreement.</span></li>
</ul>
<p><br /><br /></p>
